const city = {
	"Democratic Republic of the Congo": ["Kinshasa"],
	"Egypt": ["Alexandria","Cairo"],
	"Ethiopia":["Addis Ababa"],
	"Ivory Coast":["Abidjan"],
	"Kenya":["Nairobi","Mombasa"],
	"Morocco":["Casablanca"],
	"Namibia":["Windhoek"],
	"Nigeria":["Ibadan","Kano","Lagos"],
	"South Africa":["Cape Town","Durban","Johannesburg"],
	"Bangladesh":["Dhaka"],
	"China":["Beijing","Chengdu","Dongguan","Guangzhou","Hangzhou","Hong Kong","Shanghai","Shenzhen","Tianjin","Wuhan"],
	"India":["Ahmedabad","Bangalore","Chennai","Hyderabad","Kolkata","Mumbai","New Delhi","Pune","Surat"],
	"Indonesia":["Denpasar","Jakarta"],
	"Iran":["Tehrān"],
	"Iraq":["Baghdad"],
	"Japan":["Fukuoka","Hiroshima","Kawasaki","Kitakyushu","Kobe","Kyoto","Nagoya","Osaka","Saitama","Sapporo","Sendai","Tokyo","Yokohama"],
	"Malaysia":["Kuala Lumpur"],
	"Myanmar":["Yangon"],
	"North Korea":["Pyongyang"],
	"Pakistan":["Karachi","Lahore"],
	"Philippines":["Manila"],
	"Saudi Arabia":["Riyadh"],
	"Singapore":["Singapore"],
	"South Korea":["Busan","Seoul"],
	"Syria":["Damascus"],
	"Taiwan":["Taipei"],
	"Thailand":["Bangkok","Phuket"],
	"Turkey":["Ankara","Istanbul","İzmir"],
	"United Arab Emirates":["Dubai"],
	"Vietnam":["Ho Chi Minh City","Hà Nội"],
	"Australia":["Adelaide","Brisbane","Melbourne","Perth","Sydney"],
	"New Zealand":["Auckland","Christchurch","Manukau","Wellington"],
	"Austria":["Vienna"],
	"Belarus":["Minsk"],
	"Belgium":["Brussels"],
	"Bulgaria":["Sofia"],
	"Croatia":["Zagreb"],
	"Czech Republic":["Prague"],
	"Denmark":["Copenhagen"],
	"Finland":["Helsinki"],
	"France":["Ajaccio","Bordeaux","Calvi","Lille","Lyon","Marseille","Nice","Paris","Toulouse"],
	"Germany":["Berlin","Bremen","Cologne","Dortmund","Dresden","Düsseldorf","Essen","Frankfurt","Hamburg","Hanover","Leipzig","Munich","Nuremberg","Stuttgart"],
	"Greece":["Athens","Santorini"],
	"Hungary":["Budapest"],
	"Iceland":["Reykjavík"],
	"Ireland":["Dublin"],
	"Italy":["Milan","Naples","Rome","Torino","Venice"],
	"Netherlands":["Amsterdam","The Hague"],
	"Norway":["Oslo"],
	"Poland":["Warsaw"],
	"Portugal":["Lisbon"],
	"Romania":["Bucharest"],
	"Russia":["Moscow","St Petersburg"],
	"Spain":["Barcelona","Madrid","Santa Cruz de Tenerife","Santander"],
	"Sweden":["Gothenburg","Stockholm"],
	"Switzerland":["Gothenburg","Stockholm"],
	"Switzerland":["Geneva","Zurich"],
	"Ukraine":["Kharkiv","Kiev"],
	"United Kingdom":["Birmingham","Blackpool","Bournemouth","Bradford","Brighton","Bristol","Cambridge","Coventry","Derby","Exeter","Falmouth","Huddersfield","Ipswich","Kingston upon Hull","Leeds","Leicester","Liverpool","London","Luton","Manchester","Middlesbrough","Newcastle","Northampton","Norwich","Nottingham","Oxford","Penzance","Plymouth","Portsmouth","Preston","Reading","Salford","Sheffield","Sidmouth","Southend-on-Sea","St Ives","Stoke-on-Trent","Sunderland","Swindon","Truro","Wakefield","Wolverhampton","York","Belfast","Aberdeen","Dundee","Edinburgh","Glasgow","Kirkwall","Cardiff","Rhyl","Swansea"],
	"Canada":["Calgary","Edmonton","Montréal","Toronto","Vancouver"],
	"Mexico":["Mexico City"],
	"United States":["Birmingham","Anchorage","Mesa","Phoenix","Tucson","Little Rock","Bakersfield","Fresno","Lake Tahoe","Long Beach","Los Angeles","Mountain View","Oakland","Palm Springs","Sacramento","San Diego","San Francisco","San Jose","Santa Cruz","Colorado Springs","Boulder","Denver","Bridgeport","Wilmington","Washington DC","Jacksonville","Miami","Atlanta","Honolulu","Boise","Indianapolis","Des Moines","Wichita","Louisville","New Orleans","Portland","Baltimore","Boston","Detroit","Minneapolis","Jackson","Kansas City","St. Louis","Billings","Omaha","Las Vegas","Manchester","Newark","Albuquerque","Santa Fe","New York","Charlotte","Raleigh","Fargo","Columbus","Oklahoma City","Portland","Philadelphia","Providence","Columbia","Sioux Falls","Memphis","Nashville","Salt Lake City","Burlington","Richmond","Virginia Beach","Seattle","Charleston","Milwaukee","Cheyenne"],
	"Argentina":["Buenos Aires"],
	"Brazil":["Brasília","Rio de Janeiro","Salvador","São Paulo"],
	"Chile":["Santiago"],
	"Colombia":["Bogotá"],
	"Peru":["Lima"],
	"Venezuela":["Caracas","Maracaibo"]
}


export default city


